name: Run Tests and Generate Allure Report

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v2
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven tests and generate Allure results
        run: mvn clean verify

      # Step 8: Archive any trace files
      - name: Archive trace files
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/*.zip

      # Step 9: Deploy Allure reports to github pages
      - name: Deploy Allure reports to GitHub Pages
        if: always()  # Ensure this runs even if previous steps fail
        uses: peaceiris/action-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          publish_branch: gh-pages
          publish_dir_is_root: true
          commit_message: "Deploy Allure report"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dump-contexts-to-log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'
      - name: Dump secrets
        run: echo '${{ toJSON(secrets) }}'
      - name: Dump vars
        run: echo '${{ toJSON(vars) }}'


#      - name: Upload Allure results
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: target/allure-results