name: Run Tests and Generate Allure Report

on:

  push:
    branches: [ main ]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
  # Allows manual triggering of the workflow

jobs:
  playwright-java-cucumber-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group: [ group1, group2, group3 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests for ${{ matrix.group }}
        run: mvn clean verify -DtestGroup=${{ matrix.group }}

      # Step 8: Archive any trace files
      - name: Archive trace files
        if: always()  # Ensure this runs even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/${{ matrix.group }}-*.zip

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: target/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true
          commit_message: 'Update Allure Report for ${{ matrix.group }}'


  dump-contexts-to-log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      # - name: Dump strategy context
      #   run: echo '${{ toJSON(strategy) }}'
      # - name: Dump matrix context
      #   run: echo '${{ toJSON(matrix) }}'
      - name: Dump vars
        run: echo '${{ toJSON(vars) }}'
